### ISSUE TITLE
Vive Focus 3 to-do list

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10942]
Tracking a todo list for various outstanding issues surrounding Vive Focus 3 support. Interest from the community has been demonstrated (#10849) and it seems we don't have to do much on our end to support it! The main blocker is the ray/pinch polyfills, it seems...

Follow instructions here: https://developer.vive.com/resources/openxr/openxr-mobile/tutorials/unity/getting-started-openxr-mobile/ and make sure to delete the MRTKDevTemplate `manifest.xml`.

- [x] Head tracking + display working already (woohoo!)
- [x] Joints working already (woohoo!)
- [x] Controllers working already (woohoo!)
- [ ] Rendering bug in sample scene (mysterious large black glitchy quad/thing...)
- [ ] Pinch and ray polyfills don't seem to function, but neither does the Vive hand interaction profile
- [ ] Vive Focus 3 conflicts with the Quest-specific android manifest xml we have in our sample scene
- [ ] Passthrough, perchance?

Update Oct 4th: now blocked, as our Vive Focus 3 has been taken away from us :( Will need to find/buy/etc another one...

**Comment by mr0ng** [comment]
@Zee2 I'm following this closely and already using MRTK3 + Focus 3 to create a few things. Anything I can do to help? Let me know if you're working in a specific branch for this.

**Comment by Zee2** [comment]
> @Zee2 I'm following this closely and already using MRTK3 + Focus 3 to create a few things. Anything I can do to help? Let me know if you're working in a specific branch for this.

@mr0ng awesome! Great to hear. Have you repro'd the issues above? (i.e., no hands, etc) I have a ton (_ton_) of things on my plate right now but that's probably going to be my first step.

**Comment by mr0ng** [comment]
@Zee2 I can see my hands rendered on the Focus 3, but no raycast. I'll run a few more experiments to see what's working and what's not. I'm not using the MRTK sample scene, just MRTK3 imported into a new project from the Mixed Reality Feature Tool.

**Comment by Zee2** [comment]
Update Oct 4th: now blocked, as our Vive Focus 3 has been taken away from us :( Will need to find/buy/etc another one...

**Comment by DeakWebster** [comment]
We have a focus 3 with access to their new wrist trackers as well now. Really happy to see this elevated. They have eye trackers but I do not have access to that. Is there anything I can do to help test?

The wrist trackers can basically also double as a 6dof object tracker pretty great. They also help maintain hand location with hand tracking past a farther extent although not finger tracking. Helps with wrist rotations as well. 

To answer some things based on what I’ve learned about focus 3.

Passthrough may be a no go. Basically vive focus 3 has the ability to do pass through but they do not let you access it as far as I know. This is basically because to keep their headset approved for certain security impact levels they chose not to expose the ability to control it pass through. Perhaps that may change? Not sure. In this case focus 3 will be a VR focus headset.
