### ISSUE TITLE
[GA Blocker] API Review for General Availability

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11078]
## Describe the problem
As we prepare for GA, we need to perform a fine-grained review of all publicly exposed APIs. As we reach GA, we will be responsible for maintaining these APIs, and we should make sure they're shaped like we want them to be (and that we don't expose anything we don't intend on maintaining!)

### GA Changes
Expect this list to change/grow as we evaluate the tasks necessary for reviewing our API before GA.

#### GA Packages 
  - com.microsoft.mrtk.audio
  - com.microsoft.mrtk.core
  - com.microsoft.mrtk.input
  - com.microsoft.mrtk.spatialmanipulation
  - com.microsoft.mrtk.standardassets
  - com.microsoft.mrtk.tts.windows
  - com.microsoft.mrtk.uxcomponents
  - com.microsoft.mrtk.uxcomponents.noncanvas
  - com.microsoft.mrtk.uxcore
  - com.microsoft.mrtk.windowsspeech
  - com.microsoft.mrtk.extendedassets
  - com.microsoft.mrtk.tools

#### Post GA Packages
  - com.microsoft.mrtk.accessibility
  - com.microsoft.mrtk.data
  - com.microsoft.mrtk.diagnostics 
  
#### Test Coverage
- All new bug fixes and tasks should have new unit tests written.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11588
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11556
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11589
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11590
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11591
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11592
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11593
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11594
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11595
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11596
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11556
```

**Comment by Zee2** [comment]
@MaxWang-MS tagged you to port the MROpenXR API tooling over here ;D
