### ISSUE TITLE
Unity Hands API Integration

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11300]
## Context

Unity has released (is releasing?) a new Hands API. This issue tracks our integration with their new Hands subsystem, API, OpenXR features, etc.

## Todos

- [ ] Evaluate whether we can simply drop-in their Hands subsystem
- [ ] Figure out whether we can make our hands synthesis subsystem a sibling implementation of the new Hands subsystem
- [ ] Take a peek at comparative performance
- [ ] Unity fixes the issues with Holographic Remoting
- [ ] Evaluate how this will affect Snapdragon Spaces (probably no need for their hands subsystem, either!)

**Comment by AMollis** [comment]
Tracking this work with the following issues

- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11680
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11679
