### ISSUE TITLE
Add Progress Indicators to MRTK3

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11514]
## Overview

Port the MRTK2 progress indicators ([doc](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/ux-building-blocks/progress-indicator?view=mrtkunity-2022-05)) to MRTK3.

![Image](https://user-images.githubusercontent.com/36461279/234179988-4c57a7c9-8a03-4586-9ed4-bc1a9abe0902.png)

## Tasks

- [ ] Add a _loading bar_ indicator similar to MRTK2's ([doc](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.progressindicatorloadingbar.-ctor?view=mixed-reality-toolkit-unity-2020-dotnet-2.8.0#microsoft-mixedreality-toolkit-ui-progressindicatorloadingbar-ctor))
- [ ] Add _rotating orbs_ indicator similar to MRTK2's ([doc](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.progressindicatororbsrotator?view=mixed-reality-toolkit-unity-2020-dotnet-2.8.0))
- [ ] Add _object display_ indicator similar to MRTK2's ([doc](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.progressindicatorobjectdisplay?view=mixed-reality-toolkit-unity-2020-dotnet-2.8.0))

**Comment by AMollis** [comment]
@AMollis dupe this

**Comment by AMollis** [comment]
Closing as dupe of:

- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11480
