### ISSUE TITLE
Fix Example scenes - Cannot move some scene description panels

### ISSUE THREAD

**Issue by shaynie** [microsoft/MixedRealityToolkit-Unity#11580]
## Describe the bug

Other example scenes let you drag the entire scene contents by grabbing the description panel and moving it.  In the Dialog Example scene the description panel is locked in place.

## To reproduce

1. Load the DialogExample/DictationExample scene in the Unity editor
2. Run the scene
3. Using input simulation, note that you cannot select the description panel.

## Expected behavior

The description panel should be interactable and move the scene content.

```[tasklist]
### Tasks
- [ ] Fix Dictation Sample scene
- [ ] Fix dialog example scene
- [ ] Fix BoundsControl scene
- [ ] Fix Clipping scene
- [ ] Fix any other scenes
- [ ] Non-Canvas Object Bar Example Scene
- [ ] Non-Canvas UI Backplate Example Scene
```
