### ISSUE TITLE
Update MRTK3 min version of com.microsoft.mrtk.graphicstools.unity to latest

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11584]
# Overview
Before GA, we should update MRTK3's min version of com.microsoft.mrtk.graphicstools.unity to latest

# Tasks
- [x] Publish com.microsoft.mrtk.graphicstools.unity latest to our Feature Tool's NPM feed
- [x] Update MRTK3's package dependencies to require com.microsoft.mrtk.graphicstools.unity latest
- [x] Update MRTK3's sample to use com.microsoft.mrtk.graphicstools.unity to latest
- [x] Run manual test pass to valid new graphics tools work for Unity 2021 and 2022
