### ISSUE TITLE
Add overview documentation for various MRTK3 Core package utilities

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11594]
# Overview
MRTK3's core package has various utilities that may need to be documented better.  Perhaps we need to create an overview document that catalog's these utilities. 

# Tasks
- [ ] Determine if the following utilities need to be documented, then document.
  - [ ] How-to use for `CameraSettingsManager` 
  - [ ] Add something on gizmo visualizers, like `HandBounds` 
  - [ ] Add something about `MixedRealityRaycaster` if it's useful for developers
  - [ ] Add something about `PlayspaceUtilities`

# Parent Task
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11078
