### ISSUE TITLE
For MRTK3 GA, add comment blocks for API reference docs

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11596]
# Overview 
Various public and protected MRTK3 classes, functions, properties, and events are missing documentation `<summary>` blocks.  These need to be added.  Microsoft uses these summaries to generate API reference documents.

# Parent Task
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11078
 
# Tasks

Add Comment Blocks for API Reference Docs (GA)

### Round One
  - [x] `SpatialManipulation.ObjectManipulator.GetReferenceFrameTransform`
  - [x] `SpatialManipulation.ScaleAnchorType`
 
### Round Two 
  - [x] `CameraSettings` class
  - [x] `LabelWidthAttribute` class
  - [x] `MathExtensions.PowerOfTwoGreate=rThanOrEqualTo`
  - [x] `MathExtensions.CubicToLinearIndex`
  - [x] `MathExtensions.LinearToCubicIndex`
  - [x] `MathExtensions.ClampComponentWise`
  - [x] `RayStep` struct and some functions
  - [x] `StatefulInteractable` class
  - [x] `SystemInterfaceType` constructors
  - [x] `SystemType` public functions
  - [x] `TimedFlag` class definition
  - [x] `UXBindingProfileTemplate` properties
  - [x] `VectorExtensions` some functions
  - [x] `TextToSpeechSubsystem.Provider` class definition
  - [x] `BezierInertia` class definition, serialized field tooltips
  - [x] `FuzzyGazeInteractor.GazeRaycastHitResult` struct definition and public members
  - [x] `HandJointInteractor` public method
  - [x] `HandshapeTypes` class definition
  - [x] `InputActionPoseSource` serialized field tooltips.
  - [x] `InteractionMode` struct definition and serialized field tooltips and properties
  - [x] `InteractionModeDefinition` serialized field tooltips and properties
  - [x] `InteractionModeManager` public method
  - [x] `InterpolationType` enum values
  - [x] `MRTKHandsAggregatorSubsystem.MRTKAggregator` class definition and public members

### Round Three
  - [x] `SyntheticHandsConfig` class definition
  - [x] `SyntheticHandsSubsystem` class definition
  - [x] `ControllerSimulationSettings` some public properties
  - [x] `MRTKRayReticleVisual.ReticleVisibilitySettings` enum definition and enum values
  - [x] `SpatialManipulation.FixedDistanceConstraint`
  - [x] `SpatialManipulation.FixedRotationToUserConstraint`
  - [x] `SpatialManipulation.FixedRotationToWorldConstraint`
  - [x] `SpatialManipulation.MaintainApparentSizeConstraint`
  - [x] `SpatialManipulation.MoveAxisConstraint`
  - [x] `WindowsDictationSubsystem` class definition
  - [x] `WindowsDictationSubsystemConfig` class definition
  - [x] `WindowsKeywordRecognitionSubsystem` class definition
  - [x] `WindowsKeywordRecognitionSubsystemConfig` class definition
  - [x] `WindowsTextToSpeechSubsystem` class definition
  - [x] `BasicPressableButtonVisuals` serializable fields, public properties, and protected function
  - [x] `CanvasProxyInteractor` projected fields 
  - [x] `DialogButtonType` enum values
  - [x] `DialogDismissedEventArgs` class definition
  - [x] `ObjectBarFlowDirection` enum values
  - [x] `PressableButton.SpaceMode` enum values
  - [x] `ToggleSelectedEvent` class definition
