### ISSUE TITLE
Update MRTK3 to use latest XRI components

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11679]
## Describe the problem

MRTK3 has implemented custom components on top of XRI that can now be replaced with XRI's latest feature set. We should update MRTK3 to take advantage of these new features and deprecate MRTK3's custom components.   

The usage of these new components will be part of a new MRTK3 XR Rig.  The existing MRTK rig may then be deprecated, in favor of using the new rig. 

## Tasks

- [ ] New MRTK3 XR Rig should utilize the [XR Input Modality Manager](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.4/manual/xr-input-modality-manager.html) for switching between controller and articulated hands.  This would require [XR Hands](https://docs.unity3d.com/Packages/com.unity.xr.hands@1.1/manual/index.html), and split MRTK3's `ArticulatedHandController` into two separate controllers, one for articulated hands and one for hand controllers. (MSFT Cost Estimate: 5)
- [ ] New MRTK3 XR Rig should utilize [XR Interaction Groups](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.4/manual/xr-interaction-group.html).  This may replace the need for MRTK3's [`IInteractionModeDetectors`](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/interaction-mode-manager#detectors) and [Interaction Mode Manager](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/interaction-mode-manager). However, there still needs to be a way to disable hand rays if poking or grabbing something, so this may still require some form of the [Interaction Mode Manager](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/interaction-mode-manager).  Whatever is done, the [Interaction Mode Manager](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/interaction-mode-manager) can't interfere with the handling of UGUI like it does now (see https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11557).  (MSFT Cost Estimate: 5)
- [ ] New MRTK3 XR Rig should utilize [XR Poke Interactor](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.4/manual/xr-poke-interactor.html).  This would replace the need for MRTK3's `PokeInteractor`  (MSFT Cost Estimate: 5)
- [ ] New MRTK3 XR Rig should utilize [XR Gaze Interactor](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.3/manual/xr-gaze-interactor.html) or be extended upon for eye gaze input.  This may replace the need for MRTK3's `FuzzyGazeInteractor`.  (MSFT Cost Estimate: 5)
- [ ] Usie XRI's teleporting rays  (MSFT Cost Estimate: 3)
