### ISSUE TITLE
Polish new MRTK3 Learning Path code and create pre-release versions packages

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11676]
# Overview

The new MRTK3 learning paths utilize custom `.unitypackages` that should be posted at https://github.com/microsoft/MixedRealityLearning/releases.  

Before we can pre-release these custom packages, we need to polish the code for these code packages

- [MRTK.Tutorials.GettingStarted](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.GettingStarted)
- [MRTK.Tutorials.PCHolographicRemoting](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.PCHolographicRemoting)
- [MRTK.Tutorials.AzureSpatialAnchors](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.AzureSpatialAnchors)
- [MRTK.Tutorials.AzureCloudServices](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.AzureCloudServices)

Once code is polished, we need to create the `.unitypackages` and post them to https://github.com/microsoft/MixedRealityLearning/releases/ as version 3.0.0-pre.1

# Dependencies

- Depends On: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11674

# Tasks

- [x] Update MRTK3 packages to new org.mixedrealitytoolkit pre.18 packages
- [x] Update namespaces to new non-Microsoft namespaces.
- [x] Make sure pre-release packages use latest public MRTK3 pre-release
- [x] Add MIT license
- [x] Verify code can be used in a sample app (depends on #11674)
- [ ] Create pre-release packages for each of the four packages, versioning as 3.0.0-pre.1, and post to https://github.com/microsoft/MixedRealityLearning/releases/
