### ISSUE TITLE
Create sample Unity project with completed scenes for MRTK3 Learning Paths

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11674]
# Overview

The new MRTK3 learning paths include updated sample asset packages.  We need to create and MRTK3 app sample that utilize these packages.  

The packages to use:

- [MRTK.Tutorials.GettingStarted](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.GettingStarted)
- [MRTK.Tutorials.PCHolographicRemoting](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.PCHolographicRemoting)
- [MRTK.Tutorials.AzureSpatialAnchors](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.AzureSpatialAnchors)
- [MRTK.Tutorials.AzureCloudServices](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.AzureCloudServices)

# Tasks 

This MRTK3 app should contain scenes that represent the results of completing the following learning paths:

- [x] (@marlenaklein-msft) Sample scene for [azure-cloud-services-tutorials](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/azure-cloud-services-tutorials) (uses [MRTK.Tutorials.AzureCloudServices](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.AzureCloudServices)) 
- [x] (@marlenaklein-msft) Sample scene for [azure-spatial-anchors-tutorials](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/azure-spatial-anchors-tutorials) (uses [MRTK.Tutorials.GettingStarted](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.GettingStarted) and  [MRTK.Tutorials.AzureSpatialAnchors](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.AzureSpatialAnchors))
- [x] (@marlenaklein-msft) Sample scene for [azure-speech-services-tutorials-mrtk](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/azure-speech-services-tutorials-mrtk) (uses MRTK.Tutorials.GettingStarted](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.GettingStarted))
- [x] (@marlenaklein-msft) Sample scene for [get-started-with-object-interaction](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/get-started-with-object-interaction)
- [x] (@marlenaklein-msft) Copy over [identical tutorial](https://review.learn.microsoft.com/en-us/training/modules/mixed-reality-toolkit-project-unity/?branch=main&branchFallbackFrom=pr-en-us-36204)
- [x] (@marlenaklein-msft) Sample scene for [learn-mrtk-tutorials](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/learn-mrtk-tutorials)
- [x] Sample scene for [pc-holographic-remoting-tutorials](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/pc-holographic-remoting-tutorials) (uses [MRTK.Tutorials.PCHolographicRemoting](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.PCHolographicRemoting))
- [x] (@marlenaklein-msft) Sample scene for [place-scene-objects](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/place-scene-objects)  (uses [MRTK.Tutorials.PCHolographicRemoting](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/unitypackages/MRTK.Tutorials.PCHolographicRemoting))
- [x] (@marlenaklein-msft) Sample scene for [spatial-audio-tutorials-mrtk](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/spatial-audio-tutorials-mrtk)
- [x] (@marlenaklein-msft) Sample scene for [use-eye-tracking-voice-commands](https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners/tree/main/docs/use-eye-tracking-voice-commands)

This sample app and scenes should be placed in the https://github.com/microsoft/MixedRealityLearning repository, in a new root folder called "MRTK3 Tutorials".    The "MRTK3 Tutorials" should also contain source to the learning path `.unitypackage` files (similar to [MRTK2 tutorials](https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK%20Tutorials/Assets))
