### ISSUE TITLE
MRTK vNEXT Sprint 3

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2033]
## Overview
We're starting the third sprint for vNEXT MRTK.

May 3rd - May 15th , 2018

## Sprint Goals
- [x] Refactor Input System to work with the Mixed Reality Manager.
- [x] Build Tools and Windows Device Portal
- [ ] [#2095] Gap review of ported features to determine critical scope for MVP
- [ ] [#2092] Implement first device (Windows MR) and interact with Input System
- [ ] [#2093] MVP demo scene for InputSystem
- [ ] tbc...
