### ISSUE TITLE
vNext Task: UX Controls for Beta 2

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#3092]
# Overview
Provide foundational common UX controls & interaction patterns in Beta 2 release, achieve basic feature parity with HTK. Help developers & creators start building apps with MRTK vNext.

# Requirements
* One hand manipulation (DragAndDropHandler. Originally HandDraggable.cs)
* Two hand manipulation
* Interactables (Buttons. Including HolographicButton prefab)
* Bounding Box
* App Bar (Uses Interactables)
* Tooltip

# Acceptance Criteria
- [x] DragAndDropHandler works with HoloLens (Available in mrtk_development)
- [x] TwoHandManipulatable script & example scene ([In PR](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3323) #3323 )
- [x] Interactables script & example scene (In [feature/mrtk_interactable branch](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/feature/mrtk_interactable))
- [x] Bounding Box ([In PR](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3343). #3044 )
- [x] Tooltip (Available in mrtk_development #3343 )
- [ ] App Bar (Blocked by Interactables & Bounding Box PR. Waiting for them get merged.)

**Comment by cre8ivepark** [comment]
Status updated 12/1/2018.

**Comment by Yoyozilla** [comment]
done
