### ISSUE TITLE
Iteration Plan for January 2019

### ISSUE THREAD

**Issue by chbecker-ms** [Microsoft/MixedRealityToolkit-Unity#3351]
This is our plan for January. The goal is to complete MRTK v2 and release Beta2. The definition of complete is:

- [x] No remaining breaking changes
- [x] Feature Complete compared to HTK (except for controller rendering)
- [x] Substantial feedback from Beta1 addressed

### Planned Work
- [x] Update inconsistent naming of core system implementations #3115 @davidkline-ms
- [x] Update Unity requirement to 2018.3 #3306 @davidkline-ms
- [x] move input system to core #3328 @davidkline-ms
- [x] Moving spatial awareness system to core #3327 @davidkline-ms
- [x] Tree layout and assembly restructure to align with packaging #3341 @davidkline-ms 
- [x] Refactor Controller Mapping Profile to accept individual controller scriptable objects. #3074 
- [x] Create separate OpenVR provider assembly #3358 (blocked by #3074)
- [x] Create separate WindowsMixedReality provider assembly #3357 (blocked by #3074)
- [x] Spatial awareness interfaces changes #3326 @davidkline-ms && @radicalad
- [x] Remove requirement for IMixedRealityInputHandler<T> to be an IMixedRealityInputHandler #3295 @davidkline-ms 
- [x] Add Attribute to make sure we can migrate to data provider in V3 #3387 @davidkline-ms

**Comment by davidkline-ms** [comment]
reordered the planned work list (rough priority order). will work with @chbecker-ms and @Yoyozilla to finalize the list

**Comment by davidkline-ms** [comment]
add provider assembly work (#3356, #3357, #3358) which is currently blocked by #3074

**Comment by davidkline-ms** [comment]
moved #3233 to MRTK v3 backlog

**Comment by davidkline-ms** [comment]
Moving the following to v3. We will have a migration path for v2 profiles.

- [ ] "Device" to "DataProvider" and give each system it's own registry #3170 @davidkline-ms 
    - [ ] Implement data provider pattern for input #3330 @davidkline-ms 
    - [ ] Implement data provider pattern for spatial awareness #3329 @davidkline-ms

**Comment by davidkline-ms** [comment]
#3074, #3357, #3358, #3295 and #3387 are fixed pending PR approval.

**Comment by davidkline-ms** [comment]
will not be feature complete until Feb iteration is complete (controller model support)

**Comment by davidkline-ms** [comment]
iteration complete. all mrtk_approved changes made and merged
