### ISSUE TITLE
Iteration Plan for February 2019

### ISSUE THREAD

**Issue by chbecker-ms** [Microsoft/MixedRealityToolkit-Unity#3352]
## Documentation

- [ ] MRTK doc - MRTK v2 API Documentation #3436
- [ ] Conceptual / How-To documentation for 
   
    - [x] MRTK doc - MRTK v2 how to use the boundary system #3449
    - [x] MRTK doc - MRTK v2 how to use the spatial awareness system #3448
    - [ ] MRTK doc - MRTK v2 how to use the diagnostic system #3450
    - [x] MRTK doc - How to use MRTK v2 Packages #3441

## Additive items / fixes for February,

- [x] Updated On Device Diagnostics
- [x] update version number and license file year in preparation for beta2 release #3401
- [x] vNext Task: New Interactable Object #2607 
- [x] Diagnostics System crashes HoloLens application on start #3245 
- [x] Diagnostics placement is sporadic and displays no data  #3056 
- [ ] The "select" voice command no longer fires an event on Windows Mixed Reality #3177
- [x] NullReferenceExpection in BaseSpatialObserver.CleanupMeshObject on Hololens #3226 
- [x] Unity UI Buttons do not work with WMR Motion Controllers #3262 
- [x] [vNext][UX] Feature/mrtk interactable dev merge #3380 
- [x] IMixedRealitySpatialAwarenessSystem.GetObservers<>() returns the base type, rather than the templated type #3420 @davidkline-ms 

Moving to March 
- [ ] MRTK doc - How to use UX controls in MRTK v2 #3435
- [ ] MRTK doc - How to use MRTK v2 profile system #3438 (please see #3545)
- [ ] MRTK doc - MRTK v2 input system #3439 (we have changes coming to input system) 
- [ ] MRTK doc - Step by Step guide to move a HTK project to MRTK V2 #3433
- [ ] MRTK doc - Tutorial: moving Origami app from HTK to MRTK V2 #3434
- [ ] MRTK doc - Detailed documentation on all API changes from HTK to MRTK v2 #3437
- [ ] MRTK doc - MRTK v2 Readme Update #3440
- [ ] MRTK doc - MRTK v2 API Documentation #3436

- [ ] vNext Task: Example script/scene for Manipulation Gesture #3375
- [ ] vNext Task: Example script/scene for Navigation Gesture #3374  
- [ ] Controller visualization for OpenVR #3332 @davidkline-ms && @keveleigh 
- [ ] Controller visualization for Windows Mixed Reality #3331 @davidkline-ms && @keveleigh

**Comment by davidkline-ms** [comment]
Packaging document posted to https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/MRTK-Packages

**Comment by davidkline-ms** [comment]
Boundary system document posted to: https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/Boundary-System

**Comment by davidkline-ms** [comment]
Boundary profile documented at: https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/Boundary-Visualization-Profile

**Comment by davidkline-ms** [comment]
Spatial awareness system documented at: https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/Spatial-Awareness-System

Mesh observer profile doc: https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/Spatial-Awareness-Mesh-Observer-Profile

**Comment by Yoyozilla** [comment]
Moving some items out to March as we have make some changes in order to support HoloLens 2!

**Comment by davidkline-ms** [comment]
closing now that February is ending
