### ISSUE TITLE
March 2019 Iteration Plan

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#3540]
# RC 1 Tasks
- [ ] Controller visualization for OpenVR #3332 @davidkline-ms @keveleigh 
- [x] Controller visualization for Windows Mixed Reality #3331 @chrisfromwork 
- [ ] NuGet Infrastructure @chrisfromwork && @andreiborodin 
- [x] Service Manager proposal #3545 @davidkline-ms 
- [x]  Service Manager implementation @davidkline-ms (parts 1-3)
- [x] Core infrastructure updates for HoloLens 2 @wiwei, @keveleigh && @davidkline-ms
- [ ] The "select" voice command no longer fires an event on Windows Mixed Reality #3177
- [x] Articulated Hands @keveleigh 
- [x] Eye Tracking Support @keveleigh 
- [ ] HTK Parity @davidkline-ms && @keveleigh
- [x] Expose profiler sample rate in diagnostics profile #3536 @davidkline-ms
- [ ] Some objects not cleaned up when closing the scene #3539 @davidkline-ms
- [x] Namespace simplification #3546 @andreiborodin 

# "Skip Ahead" Tasks (RC 2 or later delivery)
- [x] Hand Simulation 
- [ ] Need ability to save scanned spatial mesh data (HoloToolkit parity) #3534 @davidkline-ms
- [ ] Need ability to load (in Unity) saved spatial mesh data (HoloToolkit parity) #3535 @davidkline-ms
- [x] vNext Task: Example script/scene for Manipulation Gesture #3375 @cre8ivepark
- [x] vNext Task: Example script/scene for Navigation Gesture #3374  @cre8ivepark 
- [ ] Updated Spectator View for Mobile for MRTK V2. #3641 @chrisfromwork 
# Ongoing Tasks
- [x] MRTK doc - MRTK v2 Readme Update #3440 @Yoyozilla 
- [x] MRTK doc - MRTK v2 API Documentation #3436 @paco-ms 
- [x] MRTK doc - MRTK v2 how to use the diagnostic system #3450 @davidkline-ms
- [ ] MRTK doc - How to use MRTK v2 profile system #3438
- [ ] MRTK doc - MRTK v2 input system #3439 @luis-valverde-ms 
- [ ] MRTK doc - MRTK v2 locomotion / teleport system
- [ ] MRTK doc - How to use UX controls in MRTK v2 #3435
- [ ] MRTK doc - Step by Step guide to move a HTK project to MRTK V2 #3433 @keveleigh 
- [ ] MRTK doc - Detailed documentation on all API changes from HTK to MRTK v2 #3437 @keveleigh 
- [ ] MRTK doc - Tutorial: moving Origami app from HTK to MRTK V2 #3434 @jessemcculloch

**Comment by davidkline-ms** [comment]
fix for #3536 is in PR (#3549)

**Comment by davidkline-ms** [comment]
example API doc page: https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Services.Teleportation.MixedRealityTeleportSystem.html
