### ISSUE TITLE
[MRTK Shell Parity] UX Controls Parity with HoloLens 2 Shell

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4200]
# RC2
## Cursor/Pointer
- [x] [#4417][PR #4446][Yoon] Asset: Replace current MRTK cursor with shell-parity cursor.
- [x] [#4418][PR #4446][Yoon] Asset: Contextual cursor icons
- [x] [#4407][PR #4526][Lars] Tether line visual fit & finish

## Button
- [x] [#4410][PR #4501][Yoon] Visual fit & finish: proximity light intensity, distance, pulse effect polish, etc...

## Bounding Box
- [x] [#4416][PR #4503][Yoon] Visual fit & finish: proximity light intensity, distance, handle color, etc.

## Slate
- [x] [#4412][PR #4514][Yoon] Audio feedback is missing
- [x] [#4513][PR #4514][Yoon] Touch point visual fit & finish

---

# GA
## Button
- [x] [#4979][**PR** #5024]Button highlight for far interaction not defined (hand ray or gaze + air-tap)
- [x] [#4977][**PR** #5049] Button's border highlighting need to be adjusted (highlight only focused one)

## Bounding Box
- [x] [#4415][**PR** #4895][John] Handles should be scaled up on hand proximity 

## Fingertip visualization
- [x] [#4411][**PR** #4836][Cameron] Match the final shell design spec
- [x] [#4561][**PR** #4836][OOBE] Fingertip cursor should converge at point of activation for buttons

## Contextual Cursor Icon
- [x] [#4332][**PR** #4995][Niall] Feature: Contextual cursor icon visualization capability
- [x] [#4471][**PR** #4995][Niall] Replace current MRTK cursor with shell-parity cursor (DefaultCursor prefab)

## Slate
- [x] [#4413][**PR** #4836][Cameron] Fingertip ring shadow on surface needed

---

#  GA+
## Button
- [x] [#4978][#5168] Button's front cage should be compressed. Currently, it moves back and penetrates through
- [x] [#4562][#5168][OOBE] Compressible button visuals tuning
- [x] [#4559][#5244][OOBE] Poke pointer position does not match shell
- [x] [#4563][OOBE] Proximity Shader GlobalProximityAssigner should use point of interaction (poke pointer position) instead of fingertip joint
- [x] [#4564][OOBE] Button 'splash visual' needs to trigger not on touch but on button press
- [x] [#4565][OOBE] PressableButton does not send release events when touches end
- [x] [#4566][OOBE] PressableButton back press logic prevents fast hands from pressing buttons
the back plate 
- [x] [#5218][Shell-Parity] Adjust fingertip proximity light size/color

## Bounding Box
- [x] [#4976] In Flattened mode, the border visualization is too thin and almost invisible

## Hand Ray
- [x] [#5355][#5403] Visual fit & finish: Line color on press, keep dotted line on focus

---

#  Post GA
## Scrollable collection
- [ ] [#4724][**Experimental** #5014][Addison] Feature: Scrollable button list from OOBE

## Bounding Box + App Bar
- [ ] [#4472][App Bar][Yoon][P2] Add 'Follow Me' button and  feature (low priority)

## Cursor
- [ ] [#4980] Cursor size should automatically be scaled up/down regardless of the distance (constant view size)

## Slate
- [x] [#4983]Follow Me behavior does not match the shell
- [x] Touchpoint visualization on the surface
- [ ] Side handles should scale horizontally, instead of rotating the window. (Both options needed?)

## Speech command confirmation label
- [ ] [#4327][Yoon] Voice Speech Command Confirmation Label

## VR Teleporation visual
- [ ] [#4409][VR] Shell-parity teleport parabolic pointer + destination marker visualization & sound effect

## Keyboard
- [ ] [System Keyboard][Yoon][P2] Create an example scene with simple forms (Alpha vs Keypad examples)

**Comment by julenka** [comment]
Don't we already largely have shell parity? Most of these interactions and controls exist. Some of them, like button and slate, have bugs that make them not as good as the shell, but it may be more effective to track those bugs individually.

**Comment by wiwei** [comment]
I think this issue is designed to be a parent issue (i.e. tracking the larger area). I don't think that there's any specific action to be taken on this specific issue itself.

**Comment by chbecker-ms** [comment]
Yes, this is the parent to other issues in ZenHub. Still experimenting...

**Comment by cre8ivepark** [comment]
I have updated the list with detailed items.

**Comment by JonathanPalmerGD** [comment]
Also is the Loss of Tracking message.

Currently applications need to build their own or use the Unity default behavior (which is a static non-localized image).
I'm building something with parity currently.

**Comment by julenka** [comment]
@cre8ivepark this was marked as to be completed in May 2019 milestone but there are items in here like #4332 that I do not think we will get to even in June, because of other higher priority items. I've removed the 1905 milestone for now. Since this feels more like a running list of items I'm not sure we want to put a milestone for this issue, just because we will probabably always have things that are not quite matching shell parity, and will need to add to this list.

**Comment by cre8ivepark** [comment]
@julenka Sounds good. I have updated the page with RC2 and RC3 section.

**Comment by julenka** [comment]
Hi @cre8ivepark I really like the splitting of GA and Future. There are a couple bugs that are in future which I actually think are bugs in functionality and therefore should be in for GA. I've updated this.

**Comment by wiwei** [comment]
Closing out GA epics
