### ISSUE TITLE
Move Hand Menu out of Experimental

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5312]
The hand menu is a popular component and most developers use it in their application. For example, in our last hack, 8/12 built applications that made heavy use of the hand menu. This work item tracks tasks to bring the hand menu out of experimental as a fully supported feature in MRTK.

# Tasks
- [ ] Write tests for hand menu
- [ ] Write documentation for hand menu
- [ ] Move sample scene and menu component out of experimental folder and into SDK/examples folder
