### ISSUE TITLE
 Code Configurability - Interactable

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5459]
Interactable is a core UX component, which needs to be configurable at runtime and instantiate-able through code.

This issue tracks issues that block usage in this way, and also tracks adding tests to ensure that this component is configurable at runtime.

**TODO**
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6105
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6103
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6101
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6509
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6179

**Completed:**
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6100
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4967
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5958
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6039
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6078
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5013
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4871
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5788
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5597
- [x] Tests for runtime instantiation (fill in tests here)

Themes:
Ultimate goal: Split logic of a theme definition from theme runtime engines. Lots of cross dependencies which causes odd configuration behavior/runtime execution (Examples: Shaders, states, etc)

- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5058
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5652
- [x] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5050

**Comment by julenka** [comment]
re-opening as not all issues are closed.

**Comment by davidkline-ms** [comment]
MRTK3 uses a new interaction system (Unity's XR Interaction Toolkit). Closing as we are unlikely to make significant changes to MRTK v2.
